spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@cluster0-shard-00-00.tvjf9.mongodb.net:27017,cluster0-shard-00-01.tvjf9.mongodb.net:27017,cluster0-shard-00-02.tvjf9.mongodb.net:27017/covid19?ssl=true&replicaSet=atlas-a1jzb1-shard-0&authSource=admin&retryWrites=true&w=majority
